/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.alarmdatasimulator.view;

import com.mycompany.alarmdatasimulator.handler.JanelaInicialHandler;
import com.mycompany.alarmdatasimulator.dominio.Alarm;

import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Tiago
 */
public class JanelaInicial extends javax.swing.JFrame {

    private JanelaInicialHandler handler;

    /**
     * Creates new form JanelaInicial
     */
    public JanelaInicial() {
        initComponents();
        init();
    }

    private void init() {
        initHandler();
        initLista();
        initTabela();
        initComboBox();
    }

    private void initHandler() {
        handler = new JanelaInicialHandler(this);
    }

    private void initLista() {
        handler.initLista();
    }

    private void initTabela() {
        handler.initTabela();
    }

    private void initComboBox() {
        handler.initComboBox();
    }

    public void enablePopoutItens(boolean addEnable, boolean editEnable, boolean delEnable) {
        menuAddAlarm.setEnabled(addEnable);
        menuEditAlarm.setEnabled(editEnable);
        menuDelAlarm.setEnabled(delEnable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupLista = new javax.swing.JPopupMenu();
        menuAddAlarm = new javax.swing.JMenuItem();
        menuEditAlarm = new javax.swing.JMenuItem();
        menuDelAlarm = new javax.swing.JMenuItem();
        panelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        panelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        comboBoxAlarm = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelResume = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuPlay = new javax.swing.JMenuItem();

        menuAddAlarm.setText("Add");
        menuAddAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddAlarmActionPerformed(evt);
            }
        });
        popupLista.add(menuAddAlarm);

        menuEditAlarm.setText("Edit");
        menuEditAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditAlarmActionPerformed(evt);
            }
        });
        popupLista.add(menuEditAlarm);

        menuDelAlarm.setText("Del");
        menuDelAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelAlarmActionPerformed(evt);
            }
        });
        popupLista.add(menuDelAlarm);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Alarms"));

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista.setComponentPopupMenu(popupLista);
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        panelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder("Table"));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabela);

        comboBoxAlarm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Cause:");

        jLabel2.setText("Consequence:");

        javax.swing.GroupLayout panelTabelaLayout = new javax.swing.GroupLayout(panelTabela);
        panelTabela.setLayout(panelTabelaLayout);
        panelTabelaLayout.setHorizontalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxAlarm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        panelTabelaLayout.setVerticalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelaLayout.createSequentialGroup()
                .addGroup(panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAlarm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelResume.setBorder(javax.swing.BorderFactory.createTitledBorder("Resume"));

        jTextPane1.setEnabled(false);
        jScrollPane3.setViewportView(jTextPane1);

        javax.swing.GroupLayout panelResumeLayout = new javax.swing.GroupLayout(panelResume);
        panelResume.setLayout(panelResumeLayout);
        panelResumeLayout.setHorizontalGroup(
            panelResumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        panelResumeLayout.setVerticalGroup(
            panelResumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );

        jMenu2.setText("Menu");

        menuOpen.setText("Open");
        jMenu2.add(menuOpen);

        menuSave.setText("Save");
        jMenu2.add(menuSave);

        menuPlay.setText("Play");
        jMenu2.add(menuPlay);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseEntered
        handler.checkPopupListItensEnable();
    }//GEN-LAST:event_listaMouseEntered

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        handler.checkPopupListItensEnable();
    }//GEN-LAST:event_listaMouseClicked

    private void menuAddAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddAlarmActionPerformed
        handler.openJanelaNewAlarm();
    }//GEN-LAST:event_menuAddAlarmActionPerformed

    private void menuDelAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelAlarmActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Confirm delete?", "Delete Alarm", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            handler.delSelectedAlarm();
        }
    }//GEN-LAST:event_menuDelAlarmActionPerformed

    private void menuEditAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditAlarmActionPerformed
        handler.openJanelaEditAlarm(lista.getSelectedIndex());
    }//GEN-LAST:event_menuEditAlarmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicial().setVisible(true);
            }
        });
    }

    public JList getLista() {
        return lista;
    }

    public JTable getTabela() {
        return tabela;
    }
    
    public JComboBox getComboBox(){
        return comboBoxAlarm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxAlarm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList lista;
    private javax.swing.JMenuItem menuAddAlarm;
    private javax.swing.JMenuItem menuDelAlarm;
    private javax.swing.JMenuItem menuEditAlarm;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuPlay;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JPanel panelLista;
    private javax.swing.JPanel panelResume;
    private javax.swing.JPanel panelTabela;
    private javax.swing.JPopupMenu popupLista;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

    public void openJanelaAlarm(Alarm alarm, boolean nameEnable) {
        JanelaAlarm janela = new JanelaAlarm(this);
        janela.setLocationRelativeTo(this);
        janela.setAlarm(alarm);
        janela.setNameEnable(nameEnable);
        janela.setVisible(true);
    }

    void addAlarmToList(Alarm alarm) {
        handler.addAlarm(alarm);
    }
}
